version: 0.0
os: linux
files:
   - source: nginx
     destination: /etc/nginx/
hooks:
   ApplicationStop:
     - location: scripts/application-stop.sh
       timeout: 180
   AfterInstall:
     - location: scripts/restart-nginx.sh
       timeout: 180


