version: 0.0
os: linux
files:
   - source: app
     destination: /srv/
   - source: nginx
     destination: /etc/nginx/
hooks:
   BeforeInstall:
     - location: scripts/BeforeInstall.sh
       timeout: 60
   AfterInstall:
     - location: scripts/AfterInstall.sh
       timeout: 60
