version: 0.1
os: linux
files:
   - source: nginx
     destination: /etc/nginx/
hooks:
   BeforeInstall:
     - location: scripts/BeforeInstall.sh
       timeout: 180
   AfterInstall:
     - location: scripts/AfterInstall.sh
       timeout: 180


